version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: dd
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
